name: Update dependencies and run unit tests

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install up to date dependencies
      run: |
        pip install poetry
        poetry update --lock
        poetry install

    - name: Run pytest unit tests
      run: |
        poetry run pytest --cov
